### ISSUE TITLE
Display feature numbers in FeatureView and FeatureGrid

### ISSUE THREAD

**Issue by shabnamkadir** [kwikteam/phy#648] opened 2015-09-22 14:55 UTC
There is no way of quickly discerning which features are being displayed in the FeatureView and FeatureGrid without recourse to this kind of labourious procedure:

```
In [90]:

gui.views

Out[90]:

[<phy.cluster.manual.view_models.StatsViewModel at 0x7fcb50fb53c8>,
 <phy.cluster.manual.view_models.FeatureGridViewModel at 0x7fcb50fb54e0>,
 <phy.cluster.manual.view_models.FeatureViewModel at 0x7fcb4df047f0>,
 <phy.cluster.manual.view_models.CorrelogramViewModel at 0x7fcb4ce71e80>,
 <phy.cluster.manual.view_models.WaveformViewModel at 0x7fcb4dfa42e8>,
 <phy.cluster.manual.view_models.TraceViewModel at 0x7fcb4ce60b00>]

In [96]:

gui.views[1].x_dim

Out[96]:

array([['time', 'time', 'time', 'time'],
       ['time', (62, 0), (62, 1), (62, 2)],
       ['time', (91, 0), (91, 1), (91, 2)],
       ['time', (87, 0), (87, 1), (87, 2)]], dtype=object)

In [97]:

gui.views[1].y_dim

Out[97]:

array([['time', (62, 0), (91, 0), (87, 0)],
       [(68, 0), (68, 0), (70, 0), (61, 0)],
       [(70, 0), (68, 1), (70, 1), (61, 1)],
       [(61, 0), (68, 2), (70, 2), (61, 2)]], dtype=object)
```

**Comment by rossant** [comment] 2015-09-22 15:05
duplicate of #164

**Closed by rossant** 2015-09-22 15:05 UTC
