### ISSUE TITLE
selecting multiple clusters has issues

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy#226] opened 2015-04-27 13:41 UTC
1) Sometimes a waveform doesn't show an appropriate number of sample waveforms (only shows 2 rather than 100 or so?)
2) Order of clusters displayed in waveform view isn't consistent with the order specified in select command 

Max thinks this happens when cluster sizes vary by a lot (i.e. one cluster has 500 spikes and another has 20000). Adding a big [in number of spikes] cluster to the selection of a bunch of small clusters results in some of the small clusters being removed (or at least not shown).

![image](https://cloud.githubusercontent.com/assets/7590975/7348678/606e13aa-eceb-11e4-8ef7-ba051037e54e.png)

**Comment by rossant** [comment] 2015-04-27 21:59
You're right, this is a [known problem](https://github.com/kwikteam/phy/blob/master/phy/cluster/manual/selector.py#L104).

Duplicate of #177, so closing this. I'll open another issue for (2).

**Closed by rossant** 2015-04-27 21:59 UTC
