### ISSUE TITLE
split with lasso doesn't seem to work properly

### ISSUE THREAD

**Issue by nsteinme** [kwikteam/phy#355] opened 2015-06-17 16:25 UTC
Here is my lasso:

![image](https://cloud.githubusercontent.com/assets/7590975/8212819/d75fe2ac-1515-11e5-9ac1-e90990e228bd.png)

And here is what I see after I press k:

![image](https://cloud.githubusercontent.com/assets/7590975/8212827/e6d67822-1515-11e5-9465-55185b04710e.png)

**Comment by rossant** [comment] 2015-06-18 20:37
hmm, cannot reproduce this... is it systematic?

might be related to #367

**Comment by nsteinme** [comment] 2015-06-22 14:43
Here is another reproduction, now with just one cluster selected and when one of the feature axes is not time (those were two of my hypotheses):

before split:
![image](https://cloud.githubusercontent.com/assets/7590975/8284508/1f79987a-18f5-11e5-86e0-86caae38ed50.png)


after split:
![image](https://cloud.githubusercontent.com/assets/7590975/8284515/2c11f492-18f5-11e5-8559-937ee80e2249.png)


Note orange points within the teal ones. I also see the same kind of thing when I do it in the feature grid rather than single feature view.

**Comment by danieljdenman** [comment] 2015-06-22 16:10
just want to second nick - i see this is as well. not with every every cluster, but more often than not.

**Comment by rossant** [comment] 2015-06-22 16:12
weird!! I'll have a look

**Comment by rossant** [comment] 2015-06-23 12:33
from a quick look, it seems that this happens when there are more spikes than what can be displayed in the feature view. so can you try to increase `features_n_spikes_max` and `features_grid_n_spikes_max` in your `~/.phy/user_settings.py` so that they are larger than the number of spikes in the clusters you want to split? let me know if it works. I'll work on an actual fix in the meantime...

**Comment by nsteinme** [comment] 2015-06-23 14:48
Yes! It does seem to work now that I did that. This is great as a
workaround for now - I think I wanted to have more spikes displayed,
anyway, now that I see it that way.

**Comment by rossant** [comment] 2015-06-23 14:49
fwiw i found the bug and i have almost fixed it...

**Comment by danieljdenman** [comment] 2015-06-23 14:58
i'm trying to find user_settings.py in my windows install - i see ~/.phy/internal_settings, but no user_settings.py. is there somewhere else to change the number of displayed spikes? or i can just wait for the bug fix.

**Comment by rossant** [comment] 2015-06-23 15:00
you have to create the text file manually..

**Comment by nippoo** [comment] 2015-06-23 15:00
you have to create the file yourself...

**Comment by nsteinme** [comment] 2015-06-23 15:00
You just make it and put it in ~/.phy/. Mine has literally these lines and
nothing else:

features_n_spikes_max_bg = 250000
features_n_spikes_max = 50000
features_grid_n_spikes_max = features_n_spikes_max

**Comment by danieljdenman** [comment] 2015-06-23 15:01
got it. thanks.

**Comment by nippoo** [comment] 2015-06-23 15:02
HA! Don't let anyone tell you that the tech support for phy is bad... ;-)

**Comment by rossant** [comment] 2015-06-23 15:04
@nippoo is it worth creating an *empty* file automatically if there is none? (with maybe just one line with a link to the doc or something) -- also we don't want to erase this file when the user reinstalls phy...

**Comment by nippoo** [comment] 2015-06-23 15:05
Yes, I actually wrote an issue for this but forgot to file it yesterday. We should create an empty file if there is none, perhaps ideally with a comment explaining where to find the list of params and their description/defaults

**Comment by rossant** [comment] 2015-06-23 16:00
this is now all fixed in an upcoming PR

**Closed** 2015-06-25 15:40 UTC
Labels: bug, component: cluster-manual, done
